"""initial schema

Revision ID: 83163041013f
Revises: 
Create Date: 2026-05-04 05:58:11.567834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83163041013f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_sent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('creator_name', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('last_synced_from_profile', sa.DateTime(), nullable=True),
    sa.Column('profile_score_at_sync', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_creator_id', sa.Integer(), nullable=True),
    sa.Column('external_release_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('notified_announced_at', sa.DateTime(), nullable=True),
    sa.Column('notified_released_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('announcement_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_creator_id'], ['tracked_creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tier_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_creator_id', sa.Integer(), nullable=True),
    sa.Column('old_tier', sa.Integer(), nullable=True),
    sa.Column('new_tier', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tracked_creator_id'], ['tracked_creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_creator_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_creator_id'], ['tracked_creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('discovery_sent_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('send_after', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_sent_id'], ['discovery_sent.id'], ),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_queue')
    op.drop_table('user_overrides')
    op.drop_table('tier_changes')
    op.drop_table('releases')
    op.drop_table('tracked_creators')
    op.drop_table('discovery_sent')
    # ### end Alembic commands ###
